# Generated by Django 4.2.1 on 2023-05-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("-name",),
                "verbose_name": "C   ategory",
                "verbose_name_plural": "categories‹",
            },
        ),
    ]
