# Generated by Django 4.2.1 on 2023-05-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("-name",),
                "verbose_name": "Category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AddField(
            model_name="productinfo",
            name="external_id",
            field=models.PositiveIntegerField(default=0, verbose_name="External id"),
            preserve_default=False,
        ),
    ]
